### PR TITLE
feat(node): add extraSecretMounts

### PR DESCRIPTION
**Pull request by michalziobro**
Hey @PierreBesson !
We have another small contribution to node helm chart. This is very similar scenario to our previous one - this time mounting extra k8s secrets as volumes to the pod.

### CODE REVIEW

**Comment by michalziobro** [comment]
hmmm, integration tests fail but it's because of `substrate-faucet` helm chart [🤔](https://emojipedia.org/thinking-face/)

**Comment by PierreBesson** [comment]
Thanks for your contribution@michalziobro ! let me check the issue of failing CI caused by the faucet chart.

**Comment by PierreBesson** [comment]
@michalziobro, the faucet test issue has been fixed, you can rebase your branch and tests should be passing now.

**Comment by michalziobro** [comment]
@PierreBesson yup, seems to be ok now

**Review by PierreBesson — APPROVED** [review]

**Pull request merged**
